en:
  languageName: English
  weight: 1

  copyright: "Copyright &copy; {{< current_year >}} Tech Valley High School. All Rights Reserved. Made with [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
  title: "TVHS Dragons : FRC 5881"

  params:
    description: "Tech Valley High School Dragons : First Robotics Competition Team 5881"
    main_cta:
      text: "Donate"
      link: "/support/"
    footer_cta:
      text: "Donate"
      link: "/support/"
    github_edit: "Edit this page on GitHub"

  menu:
    main:
    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 1

    - identifier: "resources"
      name: "Resources"
      url: "/resources/"
      weight: 2

    - identifier: "2023"
      name: "FRC 2023 - CHARGED UP"
      url: "/resources"
      weight: 1
      post: "Robot Code and CAD"
      parent: "resources"

    - identifier: "sponsors"
      name: "Sponsors"
      url: "/sponsors/"
      weight: 3

    - identifier: "support"
      name: "Support"
      url: "/support/"
      weight: 4

    - identifier: "blog"
      name: "Blog"
      url: "/blog/"
      weight: 5
