######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
logo_on_white: "/img/dragons.png"
logo_on_black: "/img/logo.png"
custom_js: []
custom_css: []

######################## custom config ####################

### default social share image (can also be set per lang) ###
images: []

github:
  repo_url: "https://github.com/FRC5881/web/blob/main"
  show_edit_link: true

social_links:
  devstats: ""
  discord: ""
  facebook: ""
  flickr: ""
  github: "https://github.com/FRC5881"
  instagram: "https://www.instagram.com/frcteam5881/"
  landscape: ""
  linkedin: "https://www.linkedin.com/company/frc-5881"
  mastodon: ""
  pinterest: ""
  rss: ""
  slack: ""
  stackoverflow: ""
  threads: ""
  twitter: ""
  x: ""
  youtube: ""

# Makes the header sticky on tall screens
sticky_header: true
# Enable search in header UI
show_search: false
